version: "3.8"

services:
  bedrock-gateway:
    build:
      context: ./src  # 指定 Docker 构建上下文
      dockerfile: Dockerfile_ecs  # 指定 Dockerfile 文件
    ports:
      - 80  # 映射端口
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_REGION: ${AWS_REGION}
      DEBUG: "true"
    restart: always  # 失败时自动重启
    networks:
      - dokploy-network  # 加入 OpenWebUI 的网络

networks:
  dokploy-network:
    external: true  # 指定为 OpenWebUI 已经在用的网络
